<a href="https://colab.research.google.com/github/ycl818/Data_python/blob/main/datascience2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
arr=np.arange(1,10)
print(arr)
print(arr.reshape(3,3))
print(arr.reshape(3,-1))   #只指定其中一維度
print(arr.reshape(-1,3))   
print(arr.reshape(-1,1,3))  # 3 1 3

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [9]:
arr.reshape(-1,1)  #has output

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
arr  #did not change array itself

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
alist = list(range(1,10))
alist.append(10) #no output

In [12]:
alist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
arr =np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
print(arr.reshape(3,-1))  #(3,4)
print(arr.reshape(-1, 3)) #(4,3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
print(arr.reshape(3,5))

ValueError: ignored

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr = arr.reshape(3,-1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
print(arr.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
arr =np.arange(1,10)
mat= arr.reshape(3,3)

In [27]:
print(arr)
print(id(arr))

[1 2 3 4 5 6 7 8 9]
139881919006000


In [28]:
print(mat)
print(id(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
139881919007040


In [29]:
mat[1,1] =5566
print(mat)

[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]


In [30]:
print(arr)

[   1    2    3    4 5566    6    7    8    9]


In [31]:
arr =np.arange(1,10)
mat= arr.copy().reshape(3,3)

In [32]:
print(arr)
print(mat)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
mat[1,1]=5566
print(mat)

[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]


In [34]:
print(arr)

[1 2 3 4 5 6 7 8 9]


#Use concatenate() function to combine arrays
###axis=0, the default is combining vertically
###axis=1, combining horizontally

In [36]:
arr_a = np.arange(1, 5).reshape(2, 2)
arr_b = np.arange(5, 9).reshape(2, 2)
print(arr_a)
print(arr_b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [38]:
print(np.concatenate([arr_a, arr_b]))         # default, axis=0
print(np.concatenate([arr_a, arr_b], axis=1)) # axis=1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#Universal func

In [39]:
input_arr = np.arange(10)
output_arr = np.power(input_arr, 2)  

print(input_arr.size)  #so power is the univeraal func
print(output_arr.size)

10
10


In [40]:
output_arr = np.exp(input_arr)
print(output_arr)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


#NumPy offers a way to define ufuncs by ourselves
##Using vectorize() to turn a scalar function into a ufunc.

###not every thing can apply in func
because of discontinue

In [42]:
def is_prime(x):
    div_cnt = 0
    for i in range(1, x+1):
        if x % i == 0:
            div_cnt += 1
        if div_cnt > 2:
            break
    return div_cnt == 2
print(type(is_prime))

<class 'function'>


In [43]:
is_prime(arr)

TypeError: ignored

In [44]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [46]:
sigmoid(0)

0.5

In [47]:
sigmoid(arr)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [52]:
def step_function(x):
    if x >= 0.5:
        return 1
    else:
        return 0

In [53]:
step_function(0.4)

0

In [55]:
arr = np.linspace(1,100)
step_function(arr)

ValueError: ignored

In [56]:
is_prime_ufunc = np.vectorize(is_prime)
print(type(is_prime_ufunc))

<class 'numpy.vectorize'>


In [58]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [59]:
is_prime_ufunc(arr)

array([False,  True,  True, False,  True, False,  True, False, False])

In [60]:
help(map)

Help on class map in module builtins:

class map(object)
 |  map(func, *iterables) --> map object
 |  
 |  Make an iterator that computes the function using arguments from
 |  each of the iterables.  Stops when the shortest iterable is exhausted.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.



In [61]:
alst = list(range(1,10))
print(alst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [62]:
is_prime(alst)

TypeError: ignored

In [64]:
print(list(map(is_prime,alst)))

[False, True, True, False, True, False, True, False, False]


In [65]:
list(filter(is_prime,arr))

[2, 3, 5, 7]

#Aggregate function
###A function where the values of multiple rows are grouped together to form a single summary value.

In [66]:
arr = np.arange(1,16)
print(arr)
print(arr.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
15


In [67]:
np.sum(arr)

120

In [76]:
arr = np.arange(1,16).reshape(3,-1)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [69]:
np.sum(arr)

120

In [70]:
np.sum(arr, axis=0)

array([18, 21, 24, 27, 30])

In [71]:
np.sum(arr, axis=1)

array([15, 40, 65])

In [74]:
np.sum(arr, axis=1, keepdims=True)

array([[15],
       [40],
       [65]])

In [78]:
np.concatenate((arr,np.sum(arr, axis=1, keepdims=True)),axis=1)

array([[ 1,  2,  3,  4,  5, 15],
       [ 6,  7,  8,  9, 10, 40],
       [11, 12, 13, 14, 15, 65]])

In [79]:
np.nan

nan

In [80]:
np.pi

3.141592653589793

In [81]:
np.inf

inf

In [83]:
np.e

2.718281828459045

In [84]:
type(np.nan)

float

In [85]:
arr = np.arange(1, 16, dtype=float)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [88]:
arr[-1]=np.nan
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. nan]


In [89]:
np.sum(arr)

nan

In [90]:
np.nansum(arr)

105.0

In [93]:
np.sum(arr[~np.isnan(arr)])

105.0

In [91]:
np.max(arr)

nan

In [92]:
np.nanmax(arr)

14.0